steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/poker:$COMMIT_SHA', '.']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/poker:$COMMIT_SHA']
# Set Region
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'config', 'set', 'compute/zone', 'us-central1-a']
# Deploy image to Compute Instace
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'compute', 'instances', 'update-container', 'instance-1' , '--container-image', 'gcr.io/$PROJECT_ID/poker:$COMMIT_SHA']
images:
- gcr.io/$PROJECT_ID/poker